# Generated by Django 4.2.5 on 2023-09-28 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, default='', help_text='Please enter your symbol', max_length=50, verbose_name='Symbol')),
                ('name', models.CharField(blank=True, default='', help_text='Please enter your name', max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Please enter your name', max_length=50, verbose_name='Name')),
                ('email', models.CharField(blank=True, default='', help_text='Please enter your email', max_length=255, verbose_name='Email')),
                ('password', models.CharField(blank=True, default='', help_text='Please enter your password', max_length=50, verbose_name='Password')),
                ('updated_dated', models.DateTimeField(auto_now=True, help_text='Please enter your update date', verbose_name='Update Date')),
                ('created_dated', models.DateTimeField(auto_now_add=True, help_text='Please enter your create date', verbose_name='Create Date')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_dated'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Buy Price')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sell Price')),
                ('shares', models.IntegerField(verbose_name='Shares')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, help_text='Please enter your transaction date', verbose_name='Transaction Date')),
                ('transaction_edit_date', models.DateTimeField(auto_now=True, help_text='Please enter your transaction edit date', verbose_name='Transaction Edit Date')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.user')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='MoneyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('transaction_type', models.CharField(default='', max_length=10, verbose_name='Transaction Type')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, help_text='Please enter your transaction date', verbose_name='Transaction Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.user')),
            ],
            options={
                'verbose_name': 'Money Transaction',
                'verbose_name_plural': 'Money Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
