# Generated by Django 4.2.5 on 2023-09-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Please enter your name', max_length=50, verbose_name='Name')),
                ('value', models.CharField(blank=True, default='', help_text='Please enter your value', max_length=50, verbose_name='Value')),
                ('image', models.ImageField(blank=True, help_text='Please enter your image', null=True, upload_to='images/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'General Setting',
                'verbose_name_plural': 'General Settings',
                'ordering': ['-name'],
            },
        ),
    ]
