# Generated by Django 4.2.5 on 2023-09-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_moneytransaction_user_alter_transaction_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sell Price'),
        ),
    ]
