# Generated by Django 4.2.5 on 2023-10-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='profit'),
        ),
    ]
