# Generated by Django 4.2.5 on 2023-10-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], default='', max_length=10, verbose_name='Transaction Type'),
        ),
    ]
