# Generated by Django 4.2.5 on 2023-10-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'buy'), ('1', 'sell')], default='', help_text='Please enter your status', max_length=50, verbose_name='status'),
        ),
    ]
